const SuperHotDrops = [
    {
        image: '/1.jpg',
        title: 'Baby chimpanzee',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Chimpanzees',
    },
    {
        image: '/2.jpg',
        title: 'Chimpanzee family portrait',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Chimpanzees',
    },
    {
        image: '/3.jpg',
        title: 'Chimpanzee scientist',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Chimpanzees',
    },

    {
        image: '/4.jpg',
        title: 'Snow monkey in hot spring',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Macaques',
    },
    {
        image: '/5.jpg',
        title: 'Lion-tailed macaque with baby',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Macaques',
    },
    {
        image: '/6.jpg',
        title: 'Black crested macaque portrait',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Macaques',
    },

    {
        image: '/7.jpg',
        title: 'White-handed gibbon',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Gibbons',
    },
    {
        image: '/8.jpg',
        title: 'Gibbon family group',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Gibbons',
    },
    {
        image: '/1.jpg',
        title: 'Lar gibbon singing',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Gibbons',
    },

    {
        image: '/2.jpg',
        title: 'Cotton-top tamarin in tree hole',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Tamarins',
    },
    {
        image: '/3.jpg',
        title: 'Tamarin mother with babies',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Tamarins',
    },
    {
        image: '/4.jpg',
        title: 'Golden lion tamarin close-up',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Tamarins',
    },

    {
        image: '/5.jpg',
        title: 'Hanuman langur with red face',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Langurs',
    },
    {
        image: '/6.jpg',
        title: 'Leaf monkey sitting in tree',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Langurs',
    },
    {
        image: '/7.jpg',
        title: 'Gray langur with baby',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Langurs',
    },

    {
        image: '/8.jpg',
        title: 'Capuchin monkey in a suit',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Capuchins',
    },
    {
        image: '/1.jpg',
        title: 'White-fronted capuchin with fruit',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Capuchins',
    },
    {
        image: '/2.jpg',
        title: 'Capuchin monkey artist',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Capuchins',
    },
]

export default SuperHotDrops
